serviceAccount: "cloud-build-default@parser-data-keys.iam.gserviceaccount.com"

options:
  logging: GCS_ONLY
  logsBucket: "gs://my-cloud-build-logs-scraper"

steps:
- name: "gcr.io/cloud-builders/docker"
  args: [
    "build",
    "-t",
    "gcr.io/$PROJECT_ID/github.com/feu-dor/scraper-app:$COMMIT_SHA",
    "."
  ]

- name: "gcr.io/cloud-builders/docker"
  args: [
    "push",
    "gcr.io/$PROJECT_ID/github.com/feu-dor/scraper-app:$COMMIT_SHA"
  ]
